# Form implementation generated from reading ui file 'design/QtDesigner/add_server.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from design.utils import translation as translation
from .themes.css import dark, light
from settings.other_settings import OtherSettings
from PyQt6 import QtCore, QtGui, QtWidgets


class AddServerWindowDesign(object):
    def setupUi(self, MainWindow, language: str):
        try:
            self.theme = OtherSettings().get()["theme"]
            self.theme = dark if self.theme == "dark" else light

        except Exception:
            pass

        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(410, 289)
        MainWindow.setStyleSheet(self.theme.background_style)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(10, 80, 391, 61))
        self.ip.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port.setGeometry(QtCore.QRect(10, 150, 391, 61))
        self.port.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.port.setObjectName("port")
        self.name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 10, 391, 61))
        self.name.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.name.setObjectName("name")
        self.add_server = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_server.setGeometry(QtCore.QRect(10, 220, 391, 61))
        self.add_server.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.add_server.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.add_server.setObjectName("add_server")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow, language)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, language):
        self.language = language
        TRANSLATION = translation.TRANSLATION[language]

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", TRANSLATION["add_server_window_title"])
        )
        self.ip.setPlaceholderText(_translate("MainWindow", TRANSLATION["ip"]))
        self.port.setPlaceholderText(_translate("MainWindow", TRANSLATION["port"]))
        self.name.setPlaceholderText(_translate("MainWindow", TRANSLATION["name"]))
        self.add_server.setText(_translate("MainWindow", TRANSLATION["add_server"]))
