# Form implementation generated from reading ui file 'design/QtDesigner/connect_to_server.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from design.utils import translation as translation
from settings.other_settings import OtherSettings
from .themes.css import dark, light


class ConnectToServerWindowDesign(object):
    def setupUi(self, MainWindow, language: str):
        try:
            self.theme = OtherSettings().get()["theme"]
            self.theme = dark if self.theme == "dark" else light

        except Exception:
            pass

        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1190, 609)
        MainWindow.setStyleSheet(self.theme.background_style)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 240, 411, 361))
        self.frame.setStyleSheet(self.theme.frame_style)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.ip = QtWidgets.QLineEdit(parent=self.frame)
        self.ip.setGeometry(QtCore.QRect(10, 10, 391, 61))
        self.ip.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.ip.setObjectName("ip")
        self.connect_to_server = QtWidgets.QPushButton(parent=self.frame)
        self.connect_to_server.setGeometry(QtCore.QRect(10, 290, 391, 61))
        self.connect_to_server.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.connect_to_server.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.connect_to_server.setObjectName("connect_to_server")
        self.nikname = QtWidgets.QLineEdit(parent=self.frame)
        self.nikname.setGeometry(QtCore.QRect(10, 150, 391, 61))
        self.nikname.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.nikname.setObjectName("nikname")
        self.port = QtWidgets.QLineEdit(parent=self.frame)
        self.port.setGeometry(QtCore.QRect(10, 80, 391, 61))
        self.port.setStyleSheet(
            "background-color: rgb(229, 229, 229);\n"
            "border-radius: 15px;\n"
            "padding-left: 5px;\n"
            "font-size: 15px"
        )
        self.port.setObjectName("port")
        self.save = QtWidgets.QPushButton(parent=self.frame)
        self.save.setGeometry(QtCore.QRect(10, 220, 391, 61))
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.save.setObjectName("save")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(430, 240, 461, 361))
        self.frame_2.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.servers = QtWidgets.QTableWidget(parent=self.frame_2)
        self.servers.setGeometry(QtCore.QRect(10, 10, 441, 201))
        self.servers.setStyleSheet(
            "background-color: rgb(184, 184, 184);\n" "border-radius: 15px;"
        )
        self.servers.setObjectName("servers")
        self.servers.setColumnCount(0)
        self.servers.setRowCount(0)
        self.add_server = QtWidgets.QPushButton(parent=self.frame_2)
        self.add_server.setGeometry(QtCore.QRect(10, 220, 211, 61))
        self.add_server.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.add_server.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.add_server.setObjectName("add_server")
        self.delete_server = QtWidgets.QPushButton(parent=self.frame_2)
        self.delete_server.setGeometry(QtCore.QRect(240, 220, 211, 61))
        self.delete_server.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.delete_server.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.delete_server.setObjectName("delete_server")
        self.apply_server = QtWidgets.QPushButton(parent=self.frame_2)
        self.apply_server.setGeometry(QtCore.QRect(10, 290, 441, 61))
        self.apply_server.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.apply_server.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.apply_server.setObjectName("apply_server")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(490, 10, 401, 221))
        self.frame_3.setStyleSheet(self.theme.frame_style)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.language_label = QtWidgets.QLabel(parent=self.frame_3)
        self.language_label.setGeometry(QtCore.QRect(10, 10, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.language_label.setFont(font)
        self.language_label.setStyleSheet("color: white;")
        self.language_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.language_label.setObjectName("language_label")
        self.translations_note = QtWidgets.QLabel(parent=self.frame_3)
        self.translations_note.setGeometry(QtCore.QRect(10, 190, 381, 20))
        self.translations_note.setStyleSheet("color: white;")
        self.translations_note.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.translations_note.setObjectName("translations_note")
        self.new_language = QtWidgets.QComboBox(parent=self.frame_3)
        self.new_language.setGeometry(QtCore.QRect(50, 70, 141, 91))
        self.new_language.setStyleSheet("background-color: none;\n" "color: black;")
        self.new_language.setObjectName("new_language")
        self.new_language.addItem("")
        self.new_language.addItem("")
        self.set_language = QtWidgets.QPushButton(parent=self.frame_3)
        self.set_language.setGeometry(QtCore.QRect(210, 70, 151, 91))
        self.set_language.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.set_language.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.set_language.setObjectName("set_language")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 471, 221))
        self.frame_4.setStyleSheet(self.theme.frame_style)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.avatar = QtWidgets.QLabel(parent=self.frame_4)
        self.avatar.setGeometry(QtCore.QRect(10, 10, 201, 201))
        self.avatar.setText("")
        self.avatar.setPixmap(QtGui.QPixmap("design/QtDesigner/../../assets/user.png"))
        self.avatar.setScaledContents(True)
        self.avatar.setObjectName("avatar")
        self.load_avatar = QtWidgets.QPushButton(parent=self.frame_4)
        self.load_avatar.setGeometry(QtCore.QRect(220, 10, 241, 91))
        self.load_avatar.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.load_avatar.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.load_avatar.setObjectName("load_avatar")
        self.delete_avatar = QtWidgets.QPushButton(parent=self.frame_4)
        self.delete_avatar.setGeometry(QtCore.QRect(220, 120, 241, 91))
        self.delete_avatar.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.delete_avatar.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.delete_avatar.setObjectName("delete_avatar")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(900, 10, 281, 591))
        self.frame_5.setStyleSheet(self.theme.frame_style)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.other_settings_label = QtWidgets.QLabel(parent=self.frame_5)
        self.other_settings_label.setGeometry(QtCore.QRect(10, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.other_settings_label.setFont(font)
        self.other_settings_label.setStyleSheet(self.theme.text_style)
        self.other_settings_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.other_settings_label.setObjectName("other_settings_label")
        self.push_messages = QtWidgets.QCheckBox(parent=self.frame_5)
        self.push_messages.setGeometry(QtCore.QRect(20, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.push_messages.setStyleSheet(self.theme.text_style)
        self.push_messages.setFont(font)
        self.push_messages.setStyleSheet("")
        self.push_messages.setChecked(False)
        self.push_messages.setTristate(False)
        self.push_messages.setObjectName("push_messages")
        self.logging = QtWidgets.QCheckBox(parent=self.frame_5)
        self.logging.setGeometry(QtCore.QRect(20, 90, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.logging.setStyleSheet(self.theme.text_style)
        self.logging.setFont(font)
        self.logging.setStyleSheet("")
        self.logging.setChecked(False)
        self.logging.setTristate(False)
        self.logging.setObjectName("logging")
        self.new_theme = QtWidgets.QComboBox(parent=self.frame_5)
        self.new_theme.setGeometry(QtCore.QRect(20, 190, 151, 91))
        self.new_theme.setStyleSheet("background-color: none;\n" "color: black;")
        self.new_theme.setObjectName("new_theme")
        self.new_theme.addItem("")
        self.new_theme.addItem("")
        self.theme_label = QtWidgets.QLabel(parent=self.frame_5)
        self.theme_label.setGeometry(QtCore.QRect(20, 130, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.theme_label.setFont(font)
        self.theme_label.setStyleSheet(self.theme.text_style)
        self.theme_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.theme_label.setObjectName("theme_label")
        self.save_other_settings = QtWidgets.QPushButton(parent=self.frame_5)
        self.save_other_settings.setGeometry(QtCore.QRect(20, 290, 251, 91))
        self.save_other_settings.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.save_other_settings.setStyleSheet(
            """QPushButton {
	background-color: rgb(123, 123, 123);
	border-radius: 15px;
}
QPushButton:hover {
	background-color: rgb(108, 108, 108);
}"""
        )
        self.save_other_settings.setObjectName("save_other_settings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow, language)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, language):
        _translate = QtCore.QCoreApplication.translate
        self.language = language

        TRANSLATION = translation.TRANSLATION[language]

        MainWindow.setWindowTitle(
            _translate("MainWindow", TRANSLATION["add_server_window_title"])
        )
        MainWindow.setWindowTitle(
            _translate("MainWindow", TRANSLATION["connect_to_server_window_title"])
        )
        self.ip.setPlaceholderText(_translate("MainWindow", TRANSLATION["ip"]))
        self.connect_to_server.setText(_translate("MainWindow", TRANSLATION["connect"]))
        self.nikname.setPlaceholderText(
            _translate("MainWindow", TRANSLATION["nikname"])
        )
        self.port.setPlaceholderText(_translate("MainWindow", TRANSLATION["port"]))
        self.save.setText(_translate("MainWindow", TRANSLATION["save"]))
        self.add_server.setText(_translate("MainWindow", TRANSLATION["add_server"]))
        self.delete_server.setText(
            _translate("MainWindow", TRANSLATION["delete_server"])
        )
        self.apply_server.setText(_translate("MainWindow", TRANSLATION["apply"]))
        self.language_label.setText(
            _translate("MainWindow", TRANSLATION["language_label"])
        )
        self.new_language.setItemText(0, _translate("MainWindow", "Українська"))
        self.new_language.setItemText(1, _translate("MainWindow", "English"))
        self.set_language.setText(_translate("MainWindow", TRANSLATION["set_language"]))
        self.translations_note.setText(
            _translate("MainWindow", TRANSLATION["translations_note"])
        )
        self.load_avatar.setText(TRANSLATION["load"])
        self.delete_avatar.setText(TRANSLATION["delete"])
        self.other_settings_label.setText(
            _translate("MainWindow", TRANSLATION["other_settings"])
        )
        self.push_messages.setText(
            _translate("MainWindow", TRANSLATION["push_messages"])
        )
        self.logging.setText(_translate("MainWindow", TRANSLATION["logging"]))
        self.new_theme.setItemText(0, _translate("MainWindow", TRANSLATION["light"]))
        self.new_theme.setItemText(1, _translate("MainWindow", TRANSLATION["dark"]))
        self.theme_label.setText(_translate("MainWindow", TRANSLATION["theme"]))
        self.save_other_settings.setText(_translate("MainWindow", TRANSLATION["save"]))
        self.push_messages.setChecked(True)

        # Налаштування таблиці серверів
        self.servers.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.servers.setColumnCount(3)
        self.servers.verticalHeader().setVisible(False)

        self.servers.setHorizontalHeaderLabels(
            [TRANSLATION["name"], TRANSLATION["ip"], TRANSLATION["port"]]
        )

        for column in range(3):
            self.servers.setColumnWidth(column, self.servers.width() // 3)
