# Form implementation generated from reading ui file 'design/QtDesigner/connect_to_server.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ConnectToServerWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(411, 292)
        MainWindow.setStyleSheet("background-color: rgb(64, 65, 62); color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_to_server = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_to_server.setGeometry(QtCore.QRect(210, 220, 191, 61))
        self.connect_to_server.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.connect_to_server.setStyleSheet("QPushButton {\n"
"    background-color: rgb(123, 123, 123);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(108, 108, 108);\n"
"}")
        self.connect_to_server.setObjectName("connect_to_server")
        self.ip = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(10, 10, 391, 61))
        self.ip.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"font-size: 15px")
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port.setGeometry(QtCore.QRect(10, 80, 391, 61))
        self.port.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"font-size: 15px")
        self.port.setObjectName("port")
        self.nikname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nikname.setGeometry(QtCore.QRect(10, 150, 391, 61))
        self.nikname.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"font-size: 15px")
        self.nikname.setObjectName("nikname")
        self.save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save.setGeometry(QtCore.QRect(10, 220, 191, 61))
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(123, 123, 123);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(108, 108, 108);\n"
"}")
        self.save.setObjectName("save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AChat - підключитися до серверу"))
        self.connect_to_server.setText(_translate("MainWindow", "Підключитися"))
        self.ip.setPlaceholderText(_translate("MainWindow", "IP"))
        self.port.setPlaceholderText(_translate("MainWindow", "Порт"))
        self.nikname.setPlaceholderText(_translate("MainWindow", "Нікнейм"))
        self.save.setText(_translate("MainWindow", "Зберегти"))
