# Form implementation generated from reading ui file 'design/QtDesigner/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindowDesign(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(921, 541)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(64, 65, 62); color: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messages = QtWidgets.QListWidget(parent=self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(10, 10, 901, 311))
        self.messages.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.messages.setStyleSheet("background-color: rgb(183, 183, 183);\n"
"border-radius: 15px;")
        self.messages.setObjectName("messages")
        self.send_message = QtWidgets.QPushButton(parent=self.centralwidget)
        self.send_message.setGeometry(QtCore.QRect(10, 400, 441, 61))
        self.send_message.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_message.setStyleSheet("QPushButton {\n"
"    background-color: rgb(123, 123, 123);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(108, 108, 108);\n"
"}")
        self.send_message.setObjectName("send_message")
        self.connect_to_server = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect_to_server.setGeometry(QtCore.QRect(10, 470, 901, 61))
        self.connect_to_server.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.connect_to_server.setStyleSheet("QPushButton {\n"
"    background-color: rgb(123, 123, 123);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(108, 108, 108);\n"
"}")
        self.connect_to_server.setObjectName("connect_to_server")
        self.exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(470, 400, 441, 61))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(123, 123, 123);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(108, 108, 108);\n"
"}")
        self.exit.setObjectName("exit")
        self.message = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.message.setGeometry(QtCore.QRect(10, 330, 901, 61))
        self.message.setStyleSheet("background-color: rgb(229, 229, 229);\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"font-size: 15px")
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AChat"))
        self.send_message.setText(_translate("MainWindow", "Відправити"))
        self.connect_to_server.setText(_translate("MainWindow", "Підключитися"))
        self.exit.setText(_translate("MainWindow", "Вийти"))
        self.message.setPlaceholderText(_translate("MainWindow", "Введіть повідомлення"))
